import Head from "next/head";
import { useState } from 'react';
import SearchBar from "@/components/SearchBar";
import TradingTable from "@/components/TradingTable";
import axios from 'axios';

const TRADINGS = [
  {
      "id": "3da1bcbf-659c-4af8-ae55-fd86be997560",
      "name": "KONDO CHRISTOPHER",
      "ticker": "AAPL",
      "inserted_at": "2024-01-29T10:18:32Z",
      "updated_at": "2024-01-29T10:18:32Z",
      "amount": "1058496",
      "market_cap": "2975178948608",
      "market_cap_percentage": 0.0001,
      "shares": 5513.0,
      "startDate": "2023-11-29",
      "job_title": "Officer"
  },
  {
      "id": "1858fdf1-41d7-4956-9201-e0a0a16ff087",
      "name": "ADAMS KATHERINE L",
      "ticker": "AAPL",
      "inserted_at": "2024-01-29T10:18:32Z",
      "updated_at": "2024-01-29T10:18:32Z",
      "amount": "23305748",
      "market_cap": "2975178948608",
      "market_cap_percentage": 0.0008,
      "shares": 123448.0,
      "startDate": "2023-11-17",
      "job_title": "General Counsel"
  },
  {
      "id": "d871b968-27ac-49eb-9cd9-98b37ed6dcc7",
      "name": "ADAMS KATHERINE L",
      "ticker": "AAPL",
      "inserted_at": "2024-01-29T10:18:32Z",
      "updated_at": "2024-01-29T10:18:32Z",
      "amount": "0",
      "market_cap": "2975178948608",
      "market_cap_percentage": 0.0,
      "shares": 123448.0,
      "startDate": "2023-11-16",
      "job_title": "General Counsel"
  },
]

export default function Home() {
  const [filterTicker, setFilterTicker] = useState('');
  const [tradingList, setTradingList] = useState([]);

  async function handleSearchClick(e) {
    e.preventDefault();
    
    const response = await axios.get(`http://localhost:4000/api/insiders/${filterTicker}/transactions`);
    setTradingList(response.data)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="navbar navbar-expand-lg bg-body-tertiary">
        <div className="container-fluid">
          <a className="navbar-brand" href="#">Canary</a>
          <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarSupportedContent">

            <SearchBar filterTicker={filterTicker} onFilterChange={setFilterTicker} onSearchClick={handleSearchClick} />
          </div>
        </div>
      </nav>
      <main className="container">
        <div className="row">
          <TradingTable tradings={tradingList} />
        </div>
      </main>
    </>
  );
}
